//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dominion.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dominion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _3_2 {
            get {
                object obj = ResourceManager.GetObject("3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _61RmHTe9sPL {
            get {
                object obj = ResourceManager.GetObject("61RmHTe9sPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ishidatami {
            get {
                object obj = ResourceManager.GetObject("ishidatami", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pp_rn1_1 {
            get {
                object obj = ResourceManager.GetObject("pp_rn1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pp_rn1_2 {
            get {
                object obj = ResourceManager.GetObject("pp_rn1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap s_ribbon0939 {
            get {
                object obj = ResourceManager.GetObject("s-ribbon0939", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap s_ribbon0940 {
            get {
                object obj = ResourceManager.GetObject("s-ribbon0940", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap s_ribbon0941 {
            get {
                object obj = ResourceManager.GetObject("s-ribbon0941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap s_ribbon0942 {
            get {
                object obj = ResourceManager.GetObject("s-ribbon0942", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap カウンター {
            get {
                object obj = ResourceManager.GetObject("カウンター", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap カウント {
            get {
                object obj = ResourceManager.GetObject("カウント", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   石工
        ///医者
        ///収税吏
        ///熟練工
        ///商人ギルド
        ///助言者
        ///伝令官
        ///肉屋
        ///パン屋
        ///広場
        ///名品
        ///予言者
        ///蝋燭職人 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ギルド {
            get {
                return ResourceManager.GetString("ギルド", resourceCulture);
            }
        }
        
        /// <summary>
        ///   闇市場
        ///公使
        ///へそくり
        ///囲郭村
        ///総督 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string プロモ {
            get {
                return ResourceManager.GetString("プロモ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 公領 {
            get {
                object obj = ResourceManager.GetObject("公領", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 冒険者 {
            get {
                object obj = ResourceManager.GetObject("冒険者", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   移動動物園
        ///馬商人
        ///占い師
        ///再建
        ///収穫
        ///狩猟団
        ///村落
        ///道化師
        ///農村
        ///馬上槍試合
        ///品評会
        ///豊穣の角笛
        ///魔女娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 収穫祭 {
            get {
                return ResourceManager.GetString("収穫祭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 呪い {
            get {
                object obj = ResourceManager.GetObject("呪い", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 地下貯蔵庫 {
            get {
                object obj = ResourceManager.GetObject("地下貯蔵庫", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   市場
        ///改築
        ///鍛冶屋
        ///金貸し
        ///木こり
        ///議事堂
        ///玉座の間
        ///研究所
        ///鉱山
        ///工房
        ///宰相
        ///祝宴
        ///祝祭
        ///書庫
        ///地下貯蔵庫
        ///庭園
        ///泥棒
        ///冒険者
        ///堀
        ///魔女
        ///密偵
        ///民兵
        ///村
        ///役人
        ///礼拝堂 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 基本 {
            get {
                return ResourceManager.GetString("基本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 堀 {
            get {
                object obj = ResourceManager.GetObject("堀", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 宰相 {
            get {
                object obj = ResourceManager.GetObject("宰相", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 密偵 {
            get {
                object obj = ResourceManager.GetObject("密偵", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 屋敷 {
            get {
                object obj = ResourceManager.GetObject("屋敷", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 属州 {
            get {
                object obj = ResourceManager.GetObject("属州", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 工房 {
            get {
                object obj = ResourceManager.GetObject("工房", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 市場 {
            get {
                object obj = ResourceManager.GetObject("市場", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 庭園 {
            get {
                object obj = ResourceManager.GetObject("庭園", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 役人 {
            get {
                object obj = ResourceManager.GetObject("役人", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 改築 {
            get {
                object obj = ResourceManager.GetObject("改築", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   青空市場
        ///隠遁者
        ///金物商
        ///狩場
        ///騎士
        ///偽造通貨
        ///救貧院
        ///狂人
        ///狂信者
        ///吟遊詩人
        ///屑屋
        ///賢者
        ///行進
        ///ゴミあさり
        ///採集者
        ///祭壇
        ///山賊の宿営地
        ///死の荷車
        ///襲撃者
        ///従者城塞
        ///立て直し
        ///地下墓地
        ///盗賊
        ///ネズミ
        ///墓暴き
        ///伯爵
        ///はみだし者
        ///秘術師
        ///武器庫
        ///浮浪児
        ///浮浪者
        ///封土
        ///物置
        ///物乞い
        ///略奪 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 暗黒時代 {
            get {
                return ResourceManager.GetString("暗黒時代", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 書庫 {
            get {
                object obj = ResourceManager.GetObject("書庫", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 木こり {
            get {
                object obj = ResourceManager.GetObject("木こり", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 村 {
            get {
                object obj = ResourceManager.GetObject("村", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 民兵 {
            get {
                object obj = ResourceManager.GetObject("民兵", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 泥棒 {
            get {
                object obj = ResourceManager.GetObject("泥棒", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   海の妖婆
        ///海賊船
        ///漁村
        ///巾着切り
        ///原住民の村
        ///航海士
        ///策士
        ///島
        ///商船
        ///真珠狩り
        ///前哨地
        ///倉庫
        ///大使
        ///隊商
        ///宝の地図
        ///探検家
        ///停泊所
        ///灯台
        ///バザー
        ///引揚水夫
        ///船着場
        ///宝物庫
        ///密輸人
        ///見張り
        ///幽霊船
        ///抑留 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 海辺 {
            get {
                return ResourceManager.GetString("海辺", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 玉座の間 {
            get {
                object obj = ResourceManager.GetObject("玉座の間", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   オアシス
        ///街道
        ///開発
        ///画策
        ///官吏
        ///義賊
        ///厩舎
        ///岐路
        ///愚者の黄金
        ///交易人
        ///公爵夫人
        ///香辛料商人
        ///坑道
        ///国境の村
        ///シルクロード
        ///信託
        ///大使館
        ///地図職人
        ///値切り屋
        ///農地
        ///不正利得
        ///辺境伯
        ///埋蔵金
        ///宿屋
        ///遊牧民の野営地
        ///よろずや に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 異郷 {
            get {
                return ResourceManager.GetString("異郷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 研究所 {
            get {
                object obj = ResourceManager.GetObject("研究所", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 礼拝堂 {
            get {
                object obj = ResourceManager.GetObject("礼拝堂", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 祝宴 {
            get {
                object obj = ResourceManager.GetObject("祝宴", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 祝祭 {
            get {
                object obj = ResourceManager.GetObject("祝祭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   石切場
        ///大市場
        ///会計所
        ///隠し財産
        ///拡張
        ///記念碑
        ///宮廷
        ///行商人
        ///玉璽
        ///銀行
        ///禁制品
        ///交易路
        ///護符
        ///司教
        ///借金
        ///造幣所
        ///大衆
        ///鍛造
        ///投機
        ///都市
        ///ならず者
        ///望楼
        ///保管庫
        ///香具師
        ///労働者の村 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 繁栄 {
            get {
                return ResourceManager.GetString("繁栄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 議事堂 {
            get {
                object obj = ResourceManager.GetObject("議事堂", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 金貨 {
            get {
                object obj = ResourceManager.GetObject("金貨", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 金貸し {
            get {
                object obj = ResourceManager.GetObject("金貸し", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 鉱山 {
            get {
                object obj = ResourceManager.GetObject("鉱山", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 銀貨 {
            get {
                object obj = ResourceManager.GetObject("銀貨", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 銅貨 {
            get {
                object obj = ResourceManager.GetObject("銅貨", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   薬師
        ///賢者の石
        ///ゴーレム
        ///支配
        ///大学
        ///使い魔
        ///弟子
        ///念視の泉
        ///ブドウ園
        ///変成
        ///薬草商
        ///錬金術師 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 錬金術 {
            get {
                return ResourceManager.GetString("錬金術", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 鍛冶屋 {
            get {
                object obj = ResourceManager.GetObject("鍛冶屋", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   大広間
        ///改良
        ///仮面舞踏会
        ///貴族
        ///共謀者
        ///交易場
        ///鉱山の村
        ///公爵
        ///拷問人
        ///詐欺師
        ///執事
        ///男爵
        ///寵臣
        ///偵察員
        ///手先
        ///鉄工所
        ///銅細工師
        ///中庭
        ///願いの井戸
        ///ハーレム
        ///破壊工作員
        ///橋
        ///秘密の部屋
        ///貧民街
        ///貢物 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string 陰謀 {
            get {
                return ResourceManager.GetString("陰謀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 魔女 {
            get {
                object obj = ResourceManager.GetObject("魔女", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
